(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d,e="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},f=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},g=f(this),h;
if("function"==typeof Object.setPrototypeOf)h=Object.setPrototypeOf;else{var k;a:{var l={l:!0},m={};try{m.__proto__=l;k=m.l;break a}catch(a){}k=!1}h=k?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var p=h,q=function(a,b){a.prototype=e(b.prototype);a.prototype.constructor=a;if(p)p(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var n=Object.getOwnPropertyDescriptor(b,c);n&&Object.defineProperty(a,c,n)}else a[c]=b[c];a.m=b.prototype};var r=function(a,b){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=50);return 0<=a?a:50},t=function(a){return a.hasAttribute("direction")?a.getAttribute("direction"):"clockwise"};var u=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},v=function(a){if(u(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&u(a))return a;return null};var w=function(){var a=HTMLElement.call(this)||this;a.a=null;a.frameWidth=0;a.frameHeight=0;return a};q(w,HTMLElement);d=w.prototype;d.connectedCallback=function(){var a=this;setTimeout(function(){if(!a.gwdIsLoaded()){var b=v(a);b?b.gwdIsLoaded()&&a.gwdLoad():a.gwdLoad()}},0)};
d.gwdLoad=function(){var a=this.parentElement.querySelector("canvas");a&&(this.a=a.getContext("2d"),this.frameWidth=parseInt(a.style.width,10),this.frameHeight=parseInt(a.style.height,10));this.b();var b=void 0===b?null:b;a=document.createEvent("CustomEvent");a.initCustomEvent("ready",!0,!0,b);this.dispatchEvent(a)};d.gwdIsLoaded=function(){return!!this.a};d.renderAnimation=function(){};d.b=function(){};
d.getSupportedSwipeDirection=function(){if("undefined"==typeof this.direction)return[0,0];switch(this.direction){case "lefttoright":return[1,0];case "righttoleft":return[-1,0];case "toptobottom":return[0,1];case "bottomtotop":return[0,-1];default:return[0,0]}};d.setDirection=function(){};d.resetDirection=function(){};var x=["direction","originpercentx","originpercenty"],y=2*Math.PI,z=function(){return w.call(this)||this};q(z,w);z.prototype.connectedCallback=function(){this.c=r(this,"originpercentx")/100;this.f=r(this,"originpercenty")/100;this.i=t(this);w.prototype.connectedCallback.call(this)};
z.prototype.attributeChangedCallback=function(a){switch(a){case "direction":this.i=t(this);break;case "originpercentx":this.c=r(this,"originpercentx")/100;this.b();break;case "originpercenty":this.f=r(this,"originpercenty")/100,this.b()}};z.prototype.b=function(){var a=this.frameWidth*Math.max(1-this.c,this.c),b=this.frameHeight*Math.max(1-this.f,this.f);this.j=Math.sqrt(a*a+b*b);this.g=this.frameWidth*this.c;this.h=this.frameHeight*this.f};
z.prototype.renderAnimation=function(a,b,c){this.a.save();this.a.beginPath();"clockwise"==this.i?this.a.arc(this.g,this.h,this.j,0,y*c):this.a.arc(this.g,this.h,this.j,-y*c,0);this.a.lineTo(this.g,this.h);this.a.clip();this.a.clearRect(0,0,this.frameWidth,this.frameHeight);this.a.drawImage(b,0,0,this.frameWidth,this.frameHeight);this.a.restore()};g.Object.defineProperties(z,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return x}}});customElements.define("gwd-radial-wipe",z);}).call(this);
